[2023-04-08T07:08:50.747+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T14:20:00+00:00 [queued]>
[2023-04-08T07:08:57.393+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T14:20:00+00:00 [queued]>
[2023-04-08T07:08:57.474+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T07:08:57.492+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 3
[2023-04-08T07:08:57.520+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T07:09:01.514+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): say_Hi> on 2023-04-06 14:20:00+00:00
[2023-04-08T07:09:02.819+0000] {standard_task_runner.py:55} INFO - Started process 13294 to run task
[2023-04-08T07:09:04.339+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'io_resto_casa', 'say_Hi', 'scheduled__2023-04-06T14:20:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/ciao.py', '--cfg-path', '/tmp/tmp0jebmywp']
[2023-04-08T07:09:05.072+0000] {standard_task_runner.py:83} INFO - Job 253: Subtask say_Hi
[2023-04-08T07:09:08.491+0000] {task_command.py:389} INFO - Running <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T14:20:00+00:00 [running]> on host cfece00ff772
[2023-04-08T07:09:13.142+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=io_resto_casa
AIRFLOW_CTX_TASK_ID=say_Hi
AIRFLOW_CTX_EXECUTION_DATE=2023-04-06T14:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-06T14:20:00+00:00
[2023-04-08T07:09:13.785+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-08T07:09:13.938+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "Doing Hi in Italian!!"']
[2023-04-08T07:09:14.867+0000] {taskinstance.py:1084} INFO - Dependencies not met for <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T14:20:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-08T07:09:15.854+0000] {taskinstance.py:1084} INFO - Dependencies not met for <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T14:20:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-08T07:09:17.424+0000] {subprocess.py:86} INFO - Output:
[2023-04-08T07:09:17.535+0000] {subprocess.py:93} INFO - Doing Hi in Italian!!
[2023-04-08T07:09:17.703+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-04-08T07:09:17.933+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-08T07:09:20.293+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=io_resto_casa, task_id=say_Hi, execution_date=20230406T142000, start_date=20230408T070854, end_date=20230408T070920
[2023-04-08T07:09:24.528+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-08T07:09:45.145+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
