[2023-04-08T07:06:42.099+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:50:00+00:00 [queued]>
[2023-04-08T07:06:43.564+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:50:00+00:00 [queued]>
[2023-04-08T07:06:43.569+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T07:06:43.578+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 3
[2023-04-08T07:06:43.592+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T07:06:45.251+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): say_Hi> on 2023-04-06 12:50:00+00:00
[2023-04-08T07:06:45.381+0000] {standard_task_runner.py:55} INFO - Started process 13236 to run task
[2023-04-08T07:06:48.409+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'io_resto_casa', 'say_Hi', 'scheduled__2023-04-06T12:50:00+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/ciao.py', '--cfg-path', '/tmp/tmpo1kwen08']
[2023-04-08T07:06:48.670+0000] {standard_task_runner.py:83} INFO - Job 245: Subtask say_Hi
[2023-04-08T07:07:08.112+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2023-04-08T07:07:09.128+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 13236. PIDs of all processes in the group: [13236]
[2023-04-08T07:07:09.167+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 13236
[2023-04-08T07:07:14.693+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=13236, status='terminated', exitcode=1, started='07:06:44') (13236) terminated with exit code 1
