[2023-04-08T07:06:24.686+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:10:00+00:00 [queued]>
[2023-04-08T07:06:28.268+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:10:00+00:00 [queued]>
[2023-04-08T07:06:28.304+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T07:06:28.314+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 3
[2023-04-08T07:06:28.319+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T07:06:41.625+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): say_Hi> on 2023-04-06 12:10:00+00:00
[2023-04-08T07:06:42.609+0000] {standard_task_runner.py:55} INFO - Started process 13235 to run task
[2023-04-08T07:06:44.665+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'io_resto_casa', 'say_Hi', 'scheduled__2023-04-06T12:10:00+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/ciao.py', '--cfg-path', '/tmp/tmpl_u_0vhk']
[2023-04-08T07:06:46.373+0000] {standard_task_runner.py:83} INFO - Job 244: Subtask say_Hi
[2023-04-08T07:07:00.426+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2023-04-08T07:07:01.419+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 13235. PIDs of all processes in the group: [13235]
[2023-04-08T07:07:01.522+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 13235
[2023-04-08T07:07:01.736+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=13235, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='07:06:42') (13235) terminated with exit code Negsignal.SIGTERM
